services:
  cisco-cli-bot:
    build: .
    container_name: cisco-cli-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./database/user_data.json:/app/database/user_data.json
