name = "cisco-cli"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[[
kv_namespaces
]]
binding = "CLI"
id = "285f68c004fd4169a9d869e4565a3bcd"
preview_id = "285f68c004fd4169a9d869e4565a3bcd"

[vars]
AI_ENABLED = "true"
